/** Native TEST-only spatial UI gate. Fake camera/XR fixtures ONLY; no device camera.
 * PLAYWRIGHT_MODULE=/absolute/installed/playwright node tests/ui/spatial.mjs
 * Run only after the lead restarts the backend and grants exclusive control.
 */
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
delete process.env.DEBUG; delete process.env.PWDEBUG;
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||"playwright");
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const url=process.env.THRESHOLD_URL||"http://127.0.0.1:8765";
const origin=new URL(url).origin;assert.equal(new URL(url).hostname,"127.0.0.1");
const output=process.env.SPATIAL_EVIDENCE_DIR||path.join(root,"evidence/spatial");await fs.mkdir(output,{recursive:true});
const files=["static/app.js","static/spatial.html","static/spatial.css","static/spatial.js","tests/ui/spatial.mjs","threshold/app.py","threshold/spatial.py","threshold/detector.py","threshold/adapters.py"];
const hashes=async()=>Object.fromEntries(await Promise.all(files.map(async file=>[file,createHash("sha256").update(await fs.readFile(path.join(root,file))).digest("hex")])));
const before=await hashes();
const result={status:"RUNNING",started_at:new Date().toISOString(),scope:"TEST software plus labelled browser fixtures. No real camera, physical AR, person localization, RF coverage, or real calls.",checks:[],cleanup:{disarmed:false,radio_target:false,unpaired:false,browser_closed:false}};
let phase="launch",runtimeErrors=0,externalRequests=0,sessionId=null;
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:"reduce"});
await context.route("**/*",route=>{if(new URL(route.request().url()).origin!==origin){externalRequests++;return route.abort("blockedbyclient");}return route.continue();});
const page=await context.newPage();page.setDefaultTimeout(7000);page.on("pageerror",()=>runtimeErrors++);
let classic=null;
await page.addInitScript(()=>{
  const F=window.__spatialFixture={cameraCalls:0,cameraMode:"deny",tracks:[],xrSupported:false,xrOverlay:true,xrDelay:false,xrCalls:0,sessions:[],hit:{x:-1,y:.2,z:-1}};
  const makeStream=()=>{const c=document.createElement("canvas");c.width=160;c.height=90;const g=c.getContext("2d");g.fillStyle="#3b4931";g.fillRect(0,0,160,90);g.fillStyle="#edf0df";g.font="12px sans-serif";g.fillText("FAKE CAMERA FIXTURE",8,44);const s=c.captureStream(2);F.tracks.push(...s.getTracks());return s;};
  const devices=navigator.mediaDevices||{};
  Object.defineProperty(devices,"getUserMedia",{configurable:true,value:async()=>{F.cameraCalls++;if(F.cameraMode==="delay")return new Promise(resolve=>{F.resolveCamera=()=>resolve(makeStream());});if(F.cameraMode==="fake")return makeStream();throw new DOMException("Fixture denial","NotAllowedError");}});
  if(!navigator.mediaDevices)Object.defineProperty(navigator,"mediaDevices",{configurable:true,value:devices});
  const identity=new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);
  class FakeSession extends EventTarget {
    constructor(){super();this.domOverlayState=F.xrOverlay?{type:"screen"}:null;this.visibilityState="visible";this.renderState={};this.endCalls=0;this.frames=new Set();this.space=new EventTarget();}
    async end(){this.endCalls++;for(const id of this.frames)cancelAnimationFrame(id);this.frames.clear();this.dispatchEvent(new Event("end"));}
    updateRenderState(value){this.renderState={...this.renderState,...value};}
    async requestReferenceSpace(type){return type==="local"?this.space:new EventTarget();}
    async requestHitTestSource(){return{cancel(){F.hitCancelled=(F.hitCancelled||0)+1;}};}
    requestAnimationFrame(callback){const id=requestAnimationFrame(time=>{this.frames.delete(id);if(!this.endCalls)callback(time,{getViewerPose:()=>({views:[{projectionMatrix:identity,transform:{inverse:{matrix:identity}}}]}),getHitTestResults:()=>[{getPose:()=>({transform:{position:F.hit}})}]});});this.frames.add(id);return id;}
    cancelAnimationFrame(id){cancelAnimationFrame(id);this.frames.delete(id);}
  }
  Object.defineProperty(navigator,"xr",{configurable:true,value:{isSessionSupported:async()=>F.xrSupported,requestSession:async(type,options)=>{F.xrCalls++;F.requestedFeatures=options.requiredFeatures;const s=new FakeSession();F.sessions.push(s);if(F.xrDelay)return new Promise(resolve=>{F.resolveXR=()=>resolve(s);});return s;}}});
  if(window.WebGLRenderingContext)WebGLRenderingContext.prototype.makeXRCompatible=async()=>{};
  window.XRWebGLLayer=class{constructor(s,g){this.framebuffer=null;this.gl=g;}getViewport(){return{x:0,y:0,width:this.gl.canvas.width,height:this.gl.canvas.height};}};
});
const check=name=>{result.checks.push(name);console.log("PASS",name);};
const safeState=async()=>{const response=await context.request.get(origin+"/api/state",{timeout:5000});assert.equal(response.status(),200);const data=await response.json();assert.equal(data.source_mode,"TEST");assert.equal(data.calls.enabled,false);if(sessionId)assert.equal(data.session_id,sessionId);return data;};
const click=async(id,p=page)=>{await safeState();await p.locator(id).click();};
const waitState=(value,p=page)=>p.waitForFunction(wanted=>document.querySelector("#alarm-state").textContent===wanted,value,{timeout:15000});
const pair=async()=>{let token=(await fs.readFile(path.join(root,".local/control-token"),"utf8")).trim();await page.locator("#token").fill(token);token="";await page.locator("#pair-submit").click();await page.locator("#dashboard").waitFor({state:"visible"});assert.equal(await page.locator("#token").inputValue(),"");await page.waitForFunction(()=>!document.querySelector("#start-camera").disabled);};
const shot=name=>page.screenshot({path:path.join(output,name+".png"),fullPage:true,animations:"disabled"});
const waitMessage=snippet=>page.waitForFunction(value=>document.querySelector("#spatial-message").textContent.includes(value),snippet);
const saveSample=async()=>{await click("#use-plan");await click("#sample-zone");await page.locator("#zone-name").fill("Front entrance TEST zone");await click("#save-zone");await waitMessage("TEST zone saved");};
const quiet=async()=>{await page.evaluate(()=>window.__quietAt=null);await page.waitForFunction(()=>{const score=Number(document.querySelector("#activity-score").textContent.replace(/,/g,""));if(!Number.isFinite(score)||score>=1.8)window.__quietAt=null;else if(window.__quietAt===null)window.__quietAt=Date.now();return window.__quietAt!==null&&Date.now()-window.__quietAt>2400;},null,{timeout:12000});};
try{
  phase="auth";await page.goto(origin+"/spatial");await page.locator("#pairing").waitFor({state:"visible"});assert.equal(await page.locator("#dashboard").isVisible(),false);
  assert.equal(await page.evaluate(()=>__spatialFixture.cameraCalls+__spatialFixture.xrCalls),0);await pair();let state=await safeState();sessionId=state.session_id;
  assert(state.spatial);if(["ARMED","ALARM","CALIBRATING"].includes(state.alarm_state)){await click("#disarm");await waitState("DISARMED");}
  await click("#target-radio");await waitMessage("radio motion");state=await safeState();if(state.spatial.zone){await click("#clear-zone");await waitMessage("cleared");}
  assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);check("paired shell; no automatic media permissions; one cookie and no browser secret storage");
  phase="plan-geometry";await click("#target-zone");await waitMessage("TEST zone entry");assert.equal(await page.locator("#calibrate").isDisabled(),true);assert.equal(await page.locator("#arm").isDisabled(),true);
  for(let i=0;i<4;i++)await page.locator("#add-corner").click();assert.equal(await page.locator(".vertex-button").count(),4);
  await page.locator(".vertex-button").nth(1).click();await page.locator("#vertex-z").fill("1.5");await page.locator("#vertex-z").press("Tab");await page.locator(".vertex-button").nth(2).click();await page.locator("#vertex-z").fill("-1.5");await page.locator("#vertex-z").press("Tab");assert.equal(await page.locator("#save-zone").isDisabled(),true);assert.match(await page.locator("#geometry-detail").textContent(),/crosses/);
  await page.locator("#sample-zone").click();await page.locator("#zone-name").fill("<img src=x> TEST zone");await click("#save-zone");await waitMessage("TEST zone saved");state=await safeState();assert.equal(state.spatial.zone.vertices.length,4);assert.equal(state.spatial.zone.coordinate_space,"test-plan");assert.equal(await page.locator("#saved-zone-detail img").count(),0);assert((await page.locator("#saved-zone-detail").textContent()).includes("<img src=x>"));
  await page.locator(".vertex-button").nth(2).click();await page.waitForTimeout(650);assert.equal(await page.locator(".vertex-button").nth(2).getAttribute("aria-pressed"),"true");
  check("corner authoring/editing; crossed outlines blocked; safe zone text; selection survives state polling");
  phase="disarmed-walk";const initialIds=new Set(state.events.map(e=>e.event_id));await click("#test-walk");await page.waitForFunction(()=>document.querySelector("#actor-label").textContent.includes("INSIDE"),null,{timeout:9000});await page.waitForTimeout(3600);state=await safeState();assert.equal(state.alarm_state,"DISARMED");assert.equal(state.events.filter(e=>!initialIds.has(e.event_id)).length,0);await click("#reset-actor");await waitMessage("reset outside");await page.waitForTimeout(900);
  check("disarmed TEST walk moves synthetic actor but creates no alarm or event");
  phase="zone-alarm";await click("#calibrate");await waitState("CALIBRATING");await waitState("READY");assert.equal(await page.locator("#arm").isDisabled(),false);await page.locator("#sound-toggle").click();await click("#arm");await waitState("ARMED");
  await click("#test-motion");await page.waitForTimeout(4000);state=await safeState();assert.equal(state.alarm_state,"ARMED");assert.equal(state.events.filter(e=>!initialIds.has(e.event_id)).length,0);check("radio motion outside the zone does not become a zone-entry event");
  await click("#test-walk");await waitState("ALARM");state=await safeState();const firstEvent=state.active_event_id;assert.equal(state.events.find(e=>e.event_id===firstEvent).type,"zone_entry");assert.equal(state.events[0].source_mode,"TEST");assert.equal(await page.locator("#alarm-title").textContent(),"Synthetic zone entry");assert((await page.locator("#events").textContent()).includes("Synthetic zone entry"));await shot("spatial-390-zone-alarm");
  classic=await context.newPage();classic.on("pageerror",()=>runtimeErrors++);await classic.goto(origin);await waitState("ALARM",classic);assert.equal(await classic.locator("#alarm-title").textContent(),"Synthetic zone entry");await click("#acknowledge",classic);await waitState("ARMED");await page.waitForTimeout(4200);state=await safeState();assert.equal(state.active_event_id,null);assert.equal(state.events.filter(e=>!initialIds.has(e.event_id)).length,1);assert.equal(state.spatial.position.inside,true);assert.equal(await page.locator("#test-walk").isDisabled(),true);
  check("one shared spatial/classic latch and acknowledgement; inside hold cannot invent another entry");
  await click("#reset-actor");await waitMessage("reset outside");await quiet();await click("#test-walk");await waitState("ALARM");await click("#reset-actor");await waitMessage("reset outside");await waitState("ALARM");await click("#disarm",classic);await waitState("DISARMED");await classic.close();classic=null;check("reset does not clear a latched alarm; classic disarm controls the same spatial detector");
  phase="transport";await page.route("**/api/state",route=>route.abort("failed"));await page.waitForFunction(()=>document.querySelector("#health-status").textContent==="Connection lost");assert.equal(await page.locator("#save-zone").isDisabled(),true);assert.equal(await page.locator("#arm").isDisabled(),true);await shot("spatial-390-transport-fault");await page.unroute("**/api/state");await page.waitForFunction(()=>document.querySelector("#connection-strip").dataset.health==="healthy");check("transport loss blocks shared arm and spatial saves; recovery is explicit");
  phase="capability-fallback";await page.locator("#start-ar").click();await page.waitForFunction(()=>document.querySelector("#capability-detail").textContent.includes("not supported"));assert.equal(await page.evaluate(()=>__spatialFixture.xrCalls),0);
  await page.evaluate(()=>Object.defineProperty(window,"isSecureContext",{value:false,configurable:true}));await page.locator("#start-camera").click();assert.match(await page.locator("#capability-detail").textContent(),/insecure HTTP/);await page.evaluate(()=>Object.defineProperty(window,"isSecureContext",{value:true,configurable:true}));
  await page.locator("#start-camera").click();await page.waitForFunction(()=>document.querySelector("#capability-detail").textContent.includes("denied"));assert.equal(await page.locator("#adapter-label").textContent(),"TEST PLAN");check("fixture unsupported AR, insecure context, and denied camera remain honest plan fallbacks");
  phase="fake-preview-privacy";await page.evaluate(()=>__spatialFixture.cameraMode="fake");await page.locator("#start-camera").click();await page.waitForFunction(()=>document.querySelector("#adapter-label").textContent==="CAMERA PREVIEW");assert.equal(await page.locator("#zone-map").isVisible(),false);assert.match(await page.locator("#capability-detail").textContent(),/NOT world-tracked/);
  await page.evaluate(()=>{Object.defineProperty(document,"hidden",{value:true,configurable:true});document.dispatchEvent(new Event("visibilitychange"));});await page.waitForFunction(()=>__spatialFixture.tracks.every(t=>t.readyState==="ended"));await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event("visibilitychange"));});await page.waitForFunction(()=>document.querySelector("#connection-strip").dataset.health==="healthy");
  await page.locator("#start-camera").click();await page.waitForFunction(()=>document.querySelector("#adapter-label").textContent==="CAMERA PREVIEW");await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent("pagehide")));await page.waitForFunction(()=>__spatialFixture.tracks.every(t=>t.readyState==="ended"));await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent("pageshow",{persisted:true})));await page.waitForFunction(()=>document.querySelector("#connection-strip").dataset.health==="healthy");
  await page.evaluate(()=>__spatialFixture.cameraMode="delay");await page.locator("#start-camera").click();await page.waitForFunction(()=>typeof __spatialFixture.resolveCamera==="function");await page.locator("#logout").click();await page.locator("#pairing").waitFor({state:"visible"});await page.evaluate(()=>__spatialFixture.resolveCamera());await page.waitForFunction(()=>__spatialFixture.tracks.every(t=>t.readyState==="ended"));assert.equal(await page.locator("#camera-preview").evaluate(v=>v.srcObject),null);await pair();
  check("fake preview is not AR; hidden/pagehide stop tracks; late camera completion after unpair is stopped");
  phase="fake-xr-privacy";await page.evaluate(()=>{__spatialFixture.xrSupported=true;__spatialFixture.xrOverlay=false;});await page.locator("#start-ar").click();await page.waitForFunction(()=>document.querySelector("#capability-detail").textContent.includes("safety controls"));assert(await page.evaluate(()=>__spatialFixture.sessions.at(-1).endCalls>0));
  await page.evaluate(()=>{__spatialFixture.xrOverlay=true;__spatialFixture.xrDelay=true;});await page.locator("#start-ar").click();await page.waitForFunction(()=>typeof __spatialFixture.resolveXR==="function");await page.locator("#logout").click();await page.locator("#pairing").waitFor({state:"visible"});await page.evaluate(()=>__spatialFixture.resolveXR());await page.waitForFunction(()=>__spatialFixture.sessions.at(-1).endCalls>0);assert.equal(await page.locator("body").evaluate(b=>b.classList.contains("xr-active")),false);await pair();
  await page.evaluate(()=>__spatialFixture.xrDelay=false);await page.locator("#start-ar").click();await page.waitForFunction(()=>document.querySelector("#adapter-label").textContent==="WEBXR HIT-TEST");assert.equal(await page.locator("#xr-capture-toggle").getAttribute("aria-pressed"),"false");assert.equal(await page.locator("#xr-add-point").isDisabled(),true);
  const prevented=await page.locator("#arm").evaluate(el=>{const event=new Event("beforexrselect",{bubbles:true,cancelable:true});el.dispatchEvent(event);return event.defaultPrevented;});assert.equal(prevented,true);
  await page.evaluate(()=>{Object.defineProperty(document,"hidden",{value:true,configurable:true});document.dispatchEvent(new Event("visibilitychange"));});assert.equal(await page.evaluate(()=>__spatialFixture.sessions.at(-1).endCalls),0);await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event("visibilitychange"));});await page.waitForFunction(()=>document.querySelector("#connection-strip").dataset.health==="healthy");
  await page.locator("#xr-capture-toggle").click();for(const hit of [{x:-1,y:.2,z:-1},{x:1,y:.2,z:-1},{x:1,y:.2,z:1},{x:-1,y:.2,z:1}]){await page.evaluate(p=>__spatialFixture.hit=p,hit);await page.waitForTimeout(50);await page.locator("#xr-add-point").click();}await page.locator("#stop-media").click();await page.waitForFunction(()=>document.querySelector("#adapter-label").textContent==="AR DRAFT DIAGRAM");await click("#save-zone");await waitMessage("AR geometry draft saved");state=await safeState();const firstFrame=state.spatial.zone.frame_id;assert.equal(state.spatial.zone.coordinate_space,"webxr-local");assert.equal(state.spatial.localization.exact_zone_verified,false);assert.equal(await page.locator("#arm").isDisabled(),true);await page.waitForFunction(()=>!document.querySelector("#calibrate").disabled);assert.equal(await page.locator("#test-walk").isDisabled(),false);assert.match(await page.locator("#actor-label").textContent(),/TEST ACTOR.*OUTSIDE.*SYNTHETIC/);
  phase="ar-draft-test-simulation";await click("#calibrate");await waitState("READY");await click("#arm");await waitState("ARMED");await click("#test-walk");await waitState("ALARM");state=await safeState();const arEvent=state.events.find(e=>e.event_id===state.active_event_id);assert.equal(arEvent.type,"zone_entry");assert.equal(arEvent.source_mode,"TEST");assert.equal(arEvent.spatial.frame_id,firstFrame);assert.equal(arEvent.spatial.coordinate_space,"webxr-local");assert.equal(arEvent.spatial.zone_id,state.spatial.zone.id);assert.equal(arEvent.spatial.zone_revision,state.spatial.zone.revision);assert.equal(arEvent.spatial.synthetic,true);assert.equal(arEvent.spatial.exact_zone_verified,false);assert.equal(arEvent.spatial.position.inside,true);assert.equal(arEvent.spatial.position.synthetic,true);assert.equal(state.calls.enabled,false);assert.match(await page.locator("#actor-label").textContent(),/TEST ACTOR.*INSIDE.*SYNTHETIC/);await shot("spatial-390-ar-draft-test-alarm");await click("#disarm");await waitState("DISARMED");await click("#reset-actor");await waitMessage("reset outside");state=await safeState();assert.equal(state.spatial.test_actor.running,false);assert.equal(state.spatial.position.inside,false);check("fixture-authored AR outline supports the same explicit TEST alarm; no real AR or localization claimed");phase="fake-xr-privacy";
  await page.locator("#start-ar").click();await page.waitForFunction(()=>document.querySelector("#adapter-label").textContent==="WEBXR HIT-TEST");assert.equal(await page.locator(".vertex-button").count(),0);await page.locator("#xr-capture-toggle").click();for(const hit of [{x:-1,y:.3,z:-1},{x:1,y:.3,z:-1},{x:0,y:.3,z:1}]){await page.evaluate(p=>__spatialFixture.hit=p,hit);await page.waitForTimeout(50);await page.locator("#xr-add-point").click();}await page.locator("#stop-media").click();await click("#save-zone");await waitMessage("AR geometry draft saved");state=await safeState();assert.notEqual(state.spatial.zone.frame_id,firstFrame);
  await page.locator("#start-ar").click();await page.waitForFunction(()=>document.querySelector("#adapter-label").textContent==="WEBXR HIT-TEST");await page.locator("#xr-capture-toggle").click();await page.locator("#xr-add-point").click();await page.evaluate(()=>__spatialFixture.sessions.at(-1).space.dispatchEvent(new Event("reset")));assert.equal(await page.locator(".vertex-button").count(),0);assert.equal(await page.locator("#xr-capture-toggle").getAttribute("aria-pressed"),"false");await page.evaluate(()=>{const s=__spatialFixture.sessions.at(-1);s.visibilityState="hidden";s.dispatchEvent(new Event("visibilitychange"));});await page.waitForFunction(()=>__spatialFixture.sessions.at(-1).endCalls>0);
  check("fake XR requires overlay and explicit capture; HUD selection prevented; new/reset frames discard registration; XR hidden/late unpair end sessions");
  phase="auth-loss";await page.evaluate(()=>__spatialFixture.cameraMode="fake");await page.locator("#start-camera").click();await page.waitForFunction(()=>document.querySelector("#adapter-label").textContent==="CAMERA PREVIEW");await page.route("**/api/state",route=>route.fulfill({status:401,contentType:"application/json",body:'{"detail":"fixture session expired"}'}));await page.locator("#pairing").waitFor({state:"visible"});await page.waitForFunction(()=>__spatialFixture.tracks.every(t=>t.readyState==="ended"));await page.unroute("**/api/state");await pair();check("auth-loss signal tears down active fake camera preview");
  phase="final-plan-layout";await saveSample();await click("#target-radio");await waitMessage("radio motion");await click("#reset-actor");await waitMessage("reset outside");
  for(const width of [320,390,1440]){await page.setViewportSize({width,height:width<500?844:1000});const bounds=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,small:[...document.querySelectorAll("button,input,summary,a")].filter(el=>el.getClientRects().length).filter(el=>{const r=el.getBoundingClientRect();return r.width<44||r.height<44;}).map(el=>el.id||el.className)}));assert.equal(bounds.overflow,false);assert.deepEqual(bounds.small,[]);await shot(`spatial-${width}-plan`);check(`${width}px no horizontal overflow and 44px visible controls`);}
  const requestTimes=[];const count=request=>{if(new URL(request.url()).pathname==="/api/state")requestTimes.push(Date.now());};page.on("request",count);await page.waitForTimeout(2100);page.off("request",count);assert(requestTimes.length<=5);check("single shared polling loop, at most five state requests in 2.1 seconds");
  assert.equal(runtimeErrors,0);assert.equal(externalRequests,0);assert.deepEqual(await hashes(),before);result.source_hashes=before;check("no uncaught runtime errors or external requests; exact source hashes unchanged during gate");result.status="PASS";
}catch(error){result.status="FAIL";result.failure={phase,error_name:error?.name||"SpatialGateError",runtime_error_count:runtimeErrors};console.error("FAIL",result.failure.error_name,"phase",phase);process.exitCode=1;}
finally{
  try{await page.unrouteAll({behavior:"ignoreErrors"});let state=await safeState();if(state.alarm_state!=="DISARMED"){await safeState();const r=await context.request.post(origin+"/api/control",{data:{action:"disarm"},headers:{Origin:origin},timeout:5000});assert.equal(r.status(),200);}state=await safeState();result.cleanup.disarmed=state.alarm_state==="DISARMED";if(state.spatial.target!=="radio-motion"){await safeState();const r=await context.request.post(origin+"/api/spatial/control",{data:{action:"set_target",target:"radio-motion"},headers:{Origin:origin},timeout:5000});assert.equal(r.status(),200);}result.cleanup.radio_target=(await safeState()).spatial.target==="radio-motion";const out=await context.request.post(origin+"/api/logout",{headers:{Origin:origin},timeout:5000});assert.equal(out.status(),200);result.cleanup.unpaired=(await context.request.get(origin+"/api/state",{timeout:5000})).status()===401;}catch(error){result.cleanup.error_name=error?.name||"CleanupError";}
  try{await context.close();await browser.close();result.cleanup.browser_closed=true;}catch(error){result.cleanup.close_error_name=error?.name||"CloseError";}
  if(!Object.values(result.cleanup).every(value=>value===true)){result.status="FAIL";process.exitCode=1;}
  result.finished_at=new Date().toISOString();result.runtime_error_count=runtimeErrors;result.external_request_count=externalRequests;result.source_hashes_before=before;
  await fs.writeFile(path.join(output,"spatial-results.json"),JSON.stringify(result,null,2)+"\n");console.log(result.status,"spatial gate",result.checks.length,"checks","cleanup",JSON.stringify(result.cleanup));
}
